safe:         false
auto:         true
server:       true
server_port:  4004
baseurl:      /
url:          http://blog.narf.io
title:        blog.narf.io
author:       Nat
email:        nat.lownes+narf@gmail.com


navigation:
  - name: 'about'
    path: '/about/'
  - name: 'github'
    path: 'http://github.com/natlownes/'
  - name: 'twitter'
    path: 'http://twitter.com/nathanield/'

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock

plugins:      ./_plugins

future:       false
lsi:          false
pygments:     false
permalink:    /:year/:month/:day/:title/
